import React from 'react';
import './HomeBlogs.css';

const cards = [
  { id: 1, title: 'How to Build Resilience in Difficult Times', body: "Resilience is the ability to bounce back from adversity and overcome challenges. In difficult times, it's important to cultivate resilience as a way to cope with stress and stay mentally and emotionally healthy. Some strategies for building resilience include practicing self-care, staying connected with supportive people, reframing negative thoughts into positive ones, and setting achievable goals. By building your resilience, you can navigate difficult times with greater ease and come out stronger on the other side.", img: "https://images.pexels.com/photos/16354468/pexels-photo-16354468.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" },
  { id: 2, title: 'The Benefits of Outdoor Exercise', body:"Exercise is important for overall health and well-being, but did you know that outdoor exercise can offer unique benefits? Research has shown that outdoor exercise can improve mood, reduce stress, and boost cognitive function compared to indoor exercise. Additionally, exposure to natural sunlight can help regulate sleep and boost vitamin D levels. Whether you prefer hiking, biking, or simply going for a walk, getting outside and moving your body can have powerful benefits for your physical and mental health.", img: "https://images.unsplash.com/photo-1682687981922-7b55dbb30892?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80" },
  { id: 3, title: 'Tips for Managing Anxiety', body: 'Anxiety is a common mental health concern that can interfere with daily life. Fortunately, there are many strategies you can use to manage anxiety and reduce symptoms. Some tips include practicing relaxation techniques like deep breathing or meditation, challenging negative thoughts, staying connected with supportive people, and seeking professional help if needed. By taking steps to manage your anxiety, you can improve your overall well-being and quality of life.', img: "https://images.unsplash.com/photo-1683520596266-b7811d63e5af?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80" },
  { id: 4, title: 'The Power of Gratitude', body: "Gratitude is a practice that involves focusing on the good in life and expressing appreciation for what you have. Research has shown that practicing gratitude can improve mood, reduce stress, and even improve physical health outcomes. Some strategies for cultivating gratitude include keeping a gratitude journal, expressing gratitude to loved ones, and focusing on the present moment. By making gratitude a regular practice, you can improve your overall outlook on life and experience greater happiness and fulfillment.", img: "https://images.pexels.com/photos/14960025/pexels-photo-14960025.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" },
  { id: 5, title: 'The Benefits of Mindful Eating', body: "Mindful eating is a practice that involves paying attention to the experience of eating, from the taste and texture of food to the sensation of fullness and satiety. This can help you develop a healthier relationship with food and improve overall health outcomes. Some strategies for practicing mindful eating include slowing down during meals, avoiding distractions like TV or phones, and tuning in to your body's hunger and fullness signals. By practicing mindful eating, you can enjoy your food more fully and improve your overall health and well-being.", img: "https://images.pexels.com/photos/15658170/pexels-photo-15658170.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" },
  { id: 6, title: 'The Importance of Sleep for Mental Health', body: 'Sleep is essential for overall health and well-being, but did you know that it can also impact mental health? Research has shown that sleep deprivation can contribute to symptoms of anxiety, depression, and other mental health concerns. Getting enough sleep, on the other hand, can improve mood, boost cognitive function, and reduce stress. Some strategies for improving sleep include practicing good sleep hygiene, creating a calming bedtime routine, and seeking professional help if needed. By prioritizing sleep, you can improve your overall mental and emotional health.', img: "https://images.pexels.com/photos/12676277/pexels-photo-12676277.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" },
  { id: 7, title: 'Strategies for Overcoming Procrastination', body: "Procrastination is a common challenge that can interfere with productivity and success. Fortunately, there are many strategies you can use to overcome procrastination and achieve your goals. Some tips include breaking tasks into smaller, more manageable steps, setting achievable deadlines, and avoiding distractions like social media or email. It's also important to address any underlying factors that may be contributing to procrastination, such as fear of failure or lack of motivation. By taking steps to overcome procrastination, you can boost your productivity and achieve greater success.", img: "https://images.pexels.com/photos/16657153/pexels-photo-16657153.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" },
  { id: 8, title: 'The Benefits of Journaling', body: 'Journaling is a practice that involves writing down your thoughts, feelings, and experiences. Research has shown that, journaling can have many benefits, including reducing stress, improving mood, and enhancing self-awareness. Some strategies for journaling include setting aside time each day to write, focusing on the present moment, and being honest and authentic in your writing. By making journaling a regular practice, you can improve your overall well-being and gain valuable insights into your thoughts and emotions.', img: "https://images.unsplash.com/photo-1683669260701-2a12766c2bb4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" },
  { id: 9, title: 'Strategies for Building Self-Confidence', body: "Self-confidence is an important trait that can help you achieve your goals and navigate life's challenges with greater ease. Fortunately, there are many strategies you can use to build self-confidence. Some tips include setting achievable goals, practicing self-care, challenging negative self-talk, and seeking out positive feedback from others. It's also important to remember that self-confidence is a skill that can be developed over time, and that setbacks and failures are a natural part of the learning process. By working to build your self-confidence, you can achieve greater success and fulfillment in life.", img: "https://images.pexels.com/photos/13046525/pexels-photo-13046525.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" },
  { id: 10, title: 'The Benefits of Gratitude in the Workplace', body: 'Gratitude is a powerful tool for building strong relationships and promoting a positive workplace culture. Research has shown that expressing gratitude can improve employee morale, reduce stress, and enhance productivity. Some strategies for cultivating gratitude in the workplace include expressing appreciation for coworkers, recognizing achievements and milestones, and practicing active listening and empathy. By making gratitude a regular practice in the workplace, you can create a more positive and supportive work environment for yourself and your colleagues.', img: "https://images.unsplash.com/photo-1683463170464-ed1dd004b92f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80" },
  { id: 11, title: 'Tips for Maintaining Work-Life Balance', body: "Maintaining a healthy work-life balance is essential for overall well-being and happiness. Some tips for achieving work-life balance include setting clear boundaries between work and personal time, practicing self-care, and seeking out flexible work arrangements when possible. It's also important to prioritize the activities and relationships that are most important to you, and to make time for them regularly. By achieving a healthy work-life balance, you can improve your overall quality of life and experience greater satisfaction and fulfillment.", img: "https://images.unsplash.com/photo-1683660108133-b173c2b4281b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80" },
  { id: 12, title: 'Strategies for Overcoming Negative Self-Talk', body: "Negative self-talk can be a major obstacle to achieving success and happiness. Fortunately, there are many strategies you can use to overcome negative self-talk and cultivate a more positive mindset. Some tips include practicing self-compassion, reframing negative thoughts into positive ones, and seeking professional help if needed. It's also important to surround yourself with supportive people who believe in you and your abilities. By taking steps to overcome negative self-talk, you can achieve greater success and happiness in life.", img: "https://images.unsplash.com/photo-1682917265568-3838d264f105?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80" },
 
 
 
 
  // Add more cards as needed
];

const HomeBlogs = () => {
  return (
    <div className="cards-container">
      {cards.map(card => (
        <div key={card.id} className={`card card-${card.id}`}>
          <div className="card-image">
            <img src={card.img} alt="" />
          </div>
          <div className="card-content">
            <h3 className="card-title">{card.title}</h3>
            <p className="card-body">{card.body}</p>
          </div>
        </div>
      ))}
    </div>
  );
};

export default HomeBlogs;
